# Generated by Django 5.2.7 on 2025-10-25 00:21

from django.db import migrations

def create_roles_and_users(apps, schema_editor):
    from django.contrib.auth.models import Group, Permission, User
    from django.contrib.contenttypes.models import ContentType

    # Crear grupos (roles)
    roles = ["Administrador", "Inventario", "Ventas"]
    grupos = {}
    for role in roles:
        grupo, created = Group.objects.get_or_create(name=role)
        grupos[role] = grupo

    # Asignar permisos (ejemplo básico)
    # Nota: aquí puedes mapear permisos más específicos
    grupos["Inventario"].permissions.set(
        Permission.objects.filter(content_type__app_label="productos")
    )
    grupos["Ventas"].permissions.set(
        Permission.objects.filter(content_type__app_label="ventas")
    )

    # Crear usuarios de ejemplo
    admin, _ = User.objects.get_or_create(username="admin")
    admin.set_password("admin123")
    admin.is_superuser = True
    admin.is_staff = True
    admin.save()
    admin.groups.add(grupos["Administrador"])

    inv_user, _ = User.objects.get_or_create(username="inventario")
    inv_user.set_password("inv123")
    inv_user.is_staff = True
    inv_user.save()
    inv_user.groups.add(grupos["Inventario"])

    ventas_user, _ = User.objects.get_or_create(username="ventas")
    ventas_user.set_password("ventas123")
    ventas_user.is_staff = True
    ventas_user.save()
    ventas_user.groups.add(grupos["Ventas"])


def delete_roles_and_users(apps, schema_editor):
    from django.contrib.auth.models import Group, User
    roles = ["Administrador", "Inventario", "Ventas"]
    Group.objects.filter(name__in=roles).delete()
    User.objects.filter(username__in=["admin", "inventario", "ventas"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_roles_and_users, delete_roles_and_users)
    ]
