# Generated by Django 5.2.7 on 2025-11-01 00:51

from django.db import migrations

def create_cliente_role(apps, schema_editor):
    from django.contrib.auth.models import Group, Permission, User

    # Crear el grupo "Clientes"
    grupo, created = Group.objects.get_or_create(name="Clientes")

    # Asignar permisos básicos
    grupo.permissions.clear()

    # Crear usuario de ejemplo asociado (opcional, útil para pruebas)
    user, _ = User.objects.get_or_create(username="cliente_demo")
    user.set_password("cliente123")
    user.is_active = True
    user.save()
    user.groups.add(grupo)


def delete_cliente_role(apps, schema_editor):
    from django.contrib.auth.models import Group, User
    Group.objects.filter(name="Clientes").delete()
    User.objects.filter(username="cliente_demo").delete()



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.RunPython(create_cliente_role, delete_cliente_role)
    ]
